src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    /**
     * @Assert\NotBlank
     */
    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $body;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

    #[ORM\Column(type: 'datetime')]
    private $updated_at;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private $category;

    #[ORM\Column(type: 'text')]
    private $image_url;

    #[ORM\Column(type: 'string', length: 255)]
    private $lead;

    #[ORM\Column(type: 'integer')]
    private $views;

    #[ORM\Column(type: 'text')]
    private $original_url;

    #[ORM\Column(type: 'string', length: 255)]
    private $original_uid;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class)]
    private $comments;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->updated_at = new \DateTimeImmutable();
        $this->views = 0;
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getUserId(): ?string
    {
        return $this->user_id;
    }

    public function setUserId(string $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCategoryId(): ?string
    {
        return $this->category_id;
    }

    public function setCategoryId(string $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(string $image_url): self
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getLead(): ?string
    {
        return $this->lead;
    }

    public function setLead(string $lead): self
    {
        $this->lead = $lead;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(int $views): self
    {
        $this->views = $views;

        return $this;
    }

    public function getOriginalUrl(): ?string
    {
        return $this->original_url;
    }

    public function setOriginalUrl(string $original_url): self
    {
        $this->original_url = $original_url;

        return $this;
    }

    public function getOriginalUid(): ?string
    {
        return $this->original_uid;
    }

    public function setOriginalUid(string $original_uid): self
    {
        $this->original_uid = $original_uid;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPostId($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPostId() === $this) {
                $comment->setPostId(null);
            }
        }

        return $this;
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Post;
use App\Message\PageParseMessage;
use App\Repository\CategoryRepository;
use App\Repository\CommentRepository;
use App\Repository\PostRepository;
use App\Scrapper;
use Doctrine\Persistence\ManagerRegistry;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;


class PostController extends AbstractController
{

    /**
     * A function to create a new post. Parses the page from the supported url and creates a new post.
     *
     * @Route("/posts/new", name="app_post_new")
     */
    public function new(Request $request, CategoryRepository $categoryRepository, PostRepository $postRepository, MessageBusInterface $messageBus, Scrapper $scrapper): Response
    {
        $post = new Post();

        $form = $this->createFormBuilder($post)
            ->add('title', TextType::class, [
                'attr' => [
                    'placeholder' => 'Article title',
                ]
            ])
            ->add('lead', TextType::class,
                [
                    'attr' => [
                        'placeholder' => 'Lead',
                    ]
                ])
            ->add('body', TextareaType::class, [
                'attr' => [
                    'placeholder' => 'Body',
                ]
            ])
            ->add('image_url', TextType::class, [
                'attr' => [
                    'placeholder' => 'Image URL',
                ]
            ])
            ->add('category', ChoiceType::class, [
                'choices' => $categoryRepository->findAll(),
                'choice_label' => 'name',
                'choice_value' => 'id',
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Create Post', 'attr' => [
                    'class' => 'btn btn-primary rounded p-3'
                ]
            ])
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Post $post */
            $post = $form->getData();
            try {
                if (filter_var($post->getBody(), FILTER_VALIDATE_URL)) {
                    $data = $scrapper->parsePage($post->getBody());
                    $post->setTitle($data['title']);
                    $post->setLead($data['lead'] ?? $data['title']);
                    $post->setBody($data['body']);
                    $post->setImageUrl($data['image_url']);
                    $post->setOriginalUid($data['original_uid']);
                    $post->setOriginalUrl($data['original_url']);
                }
                else{
                    $post->setOriginalUrl('');
                    $post->setOriginalUid('');
                }

                $postRepository->add($post);
                $scrapper->parseAdditionalLinks($post);
            } catch (\Exception $e) {
                dd($e);
                return $this->redirectToRoute('app_post_new');
            }

//            $messageBus->dispatch(new PageParseMessage($post));

            return $this->redirectToRoute('app_post_show', ['post_id' => $post->getId()]);
        }

        return $this->renderForm('posts/new.html.twig', ['form' => $form]);
    }

    /**
     * A function to show list of posts.
     *
     * @Route("/posts", name="app_post_index")
     */
    public function index(CategoryRepository $categoryRepository, PostRepository $postRepository): Response
    {
        return $this->render('posts/index.html.twig', [
            'controller_name' => 'PostController',
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    /**
     * Shows a post. Increments the view count and category view count.
     *
     * @Route("/posts/{post_id}", name="app_post_show")
     */
    public function show(Request $request, $post_id, ManagerRegistry $doctrine, CommentRepository $commentRepository): Response
    {
        $entityManager = $doctrine->getManager();
        $post = $entityManager->getRepository(Post::class)->find($post_id);
        if (!$post) {
            throw $this->createNotFoundException(
                'No product found for id ' . $post_id
            );
        }
        $category = $post->getCategory();
        $category->setViews($category->getViews() + 1);
        $post->setViews($post->getViews() + 1);
        $entityManager->flush();


        $comment = new Comment();
        $form = $this->createFormBuilder($comment)
            ->add('content', TextareaType::class, [
                'label' => 'Write your comment',
                'attr' => [
                    'placeholder' => 'Content',
                ]
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Post Comment', 'attr' => [
                    'class' => 'btn btn-primary rounded p-3'
                ]
            ])
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
            /** @var Comment $comment */
            $comment = $form->getData();
            $comment->setUser($this->getUser());
            $comment->setPost($post);

            $commentRepository->add($comment);
        }


        return $this->renderForm('posts/show.html.twig', [
            'controller_name' => 'PostController',
            'post' => $post,
            'form' => $form,
        ]);


//        return $this->redirectToRoute('app_post_index');
//            throw $this->createNotFoundException('Post not found');

    }

    /**
     * Manuallly parse a page. Parses all found links in content and it's children.
     *
     * @Route("/posts/{post_id}/parse", name="app_post_parse")
     * @param $post_id
     * @return Response
     */
    public function parseLinks($post_id, Scrapper $scrapper, PostRepository $postRepository): Response
    {
        $post = $postRepository->find($post_id);
        $scrapper->parseAdditionalLinks($post, 20);
        return $this->redirectToRoute('app_post_show', ['post_id' => $post_id]);
    }


    public function featuredCards(PostRepository $postRepository, $category = null)
    {
        return $this->render('posts/featured_cards.html.twig', [
            'posts' => $postRepository->findSortedByViews(0, 3, $category)
        ]);
    }


}


/*
 * tasks
 * 1. 2 entities: Post, Category. one-to-many relationship
 * 2. Symfony security bundle. User auth/registration
 * 3. Comments for posts
 */

templates/posts/category.html.twig
<div class="p-3 glass rounded mb-3 category-heading d-flex align-items-center justify-content-between position-relative">
    <h2 class="fst-italic">{{ category.name }}</h2>
    <a href="/categories/{{ category.id }}" class="stretched-link">go to category ></a>
</div>
<div class="row mb-5">
    {% if category.getTopPosts(6) is empty %}
        <div class="col-md-12">
            <div class="p-4 glass rounded d-flex flex-column align-items-center">
                <img src="https://img.icons8.com/external-smashingstocks-glyph-smashing-stocks/66/FFFFFF/external-page-not-found-user-interface-smashingstocks-glyph-smashing-stocks.png"/>
                No posts found in this category
            </div>
        </div>
    {% endif %}
    {% for post in category.getTopPosts(6) %}
        <div class="col-md-6 col-md-auto">
            {{ include('posts/cards/post.html.twig', {'post': post}) }}
        </div>
    {% endfor %}
</div>

templates/posts/featured_cards.html.twig
{% if (posts[0] is defined) %}
    {{ include('posts/cards/featured_big.html.twig', {post: posts[0]}) }}
{% endif %}

{% if ( (posts[1] is defined and posts[1] != null) and (posts[2] is defined and posts[2] != null)) %}
    <div class="row mb-2">
        <div class="col-md-6 ">
            {{ include('posts/cards/featured_small.html.twig', {post:posts[1]}) }}
        </div>
        <div class="col-md-6 ">
            {{ include('posts/cards/featured_small.html.twig', {post:posts[2]}) }}
        </div>
    </div>
{% endif %}

templates/posts/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Posts{% endblock %}

{% block page_content %}
    {{ include('posts/recent.html.twig', {categories: categories}) }}
{% endblock %}

templates/posts/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}New{% endblock %}
{% block featured %}
{% endblock %}
{% block page_content %}
    <div class="glass rounded p-3">

        {{ form(form) }}
    </div>
{% endblock %}

templates/posts/post_card.html.twig
<div style="border: solid 1px green">
    <h1>{{ post.title }}</h1>
    <p>{{ post.body }}</p>
</div>

templates/posts/recent.html.twig
{% for category in categories %}
    <div>
        {{ include('posts/category.html.twig', {category:category}) }}
    </div>
{% endfor %}

templates/posts/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ post.title }}{% endblock %}

{% block featured %}

{% endblock %}
{% block page_content %}
    <img src="{{ post.imageUrl?post.imageUrl:'https://picsum.photos/1920/1080' }}" alt=""
         class="rounded col-12 responsive bg-thumbnail mb-3">
    <h1 class="mb-3 glass p-3 rounded">{{ post.title }}</h1>
    <div class="glass darker rounded p-3 mb-3">
        <p>{{ post.body | raw }}</p>
    </div>

    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <div class="glass rounded p-3 mb-3">
            {{ form(form) }}
        </div>
    {% endif %}

    {% if post.comments is not empty %}
        <div class="glass rounded p-2 mb-2">
            <h2>Comments</h2>
        </div>
        {% for comment in post.comments|reverse %}
            <div class="glass rounded p-3 mb-2">
                <small>
                    {{ comment.user.email }}
                </small>
                <p class="mb-0">
                    {{ comment.content }}
                </p>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}